[package]
distribution = "2201.13.1"
org = "ballerinax"
name = "ai.memory.redis"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Type/Connector", "Vendor/Redis", "Area/AI & Machine Learning", "Area/Database"]
repository = "https://github.com/ballerina-platform/module-ballerinax-ai.memory.redis"
icon="icon.png"

[platform.java21]
graalvmCompatible = true

